// ai-baseline-kit/templates/vue3-vite-ts/src/app/AppShell.vue
<script setup lang="ts">
import { RouterLink, RouterView, useRoute } from 'vue-router';
import { computed } from 'vue';
import { modules } from './module-assembler';

const route = useRoute();
const menus = modules.flatMap((module) => module.menus);
const currentPath = computed(() => route.path);
</script>

<template>
  <div class="app-shell">
    <aside class="sidebar">
      <div class="brand">AI Baseline</div>
      <nav class="menu" aria-label="主导航">
        <RouterLink
          v-for="menu in menus"
          :key="menu.key"
          :to="menu.path"
          class="menu-link"
          :class="{ active: currentPath === menu.path }"
        >
          {{ menu.label }}
        </RouterLink>
      </nav>
    </aside>
    <main class="main-content">
      <header class="topbar">
        <strong>默认 Vue 3 项目模板</strong>
        <span>Vue 3 · Vite · TypeScript</span>
      </header>
      <section class="page-content">
        <RouterView />
      </section>
    </main>
  </div>
</template>

// ai-baseline-kit/templates/react18-antd-tailwind-ts/src/app/AppShell.tsx
import { Layout, Menu } from 'antd';
import { Outlet, useLocation, useNavigate } from 'react-router-dom';
import { modules } from '@/app/module-assembler';

const { Header, Content, Sider } = Layout;
const menus = modules.flatMap((module) => module.menus);

export function AppShell() {
  const navigate = useNavigate();
  const location = useLocation();

  return (
    <Layout className="app-layout min-h-screen">
      <Sider className="app-sider" breakpoint="lg" collapsedWidth="0">
        <div className="app-brand">AI Baseline</div>
        <Menu
          theme="dark"
          mode="inline"
          selectedKeys={[location.pathname]}
          items={menus.map((menu) => ({ key: menu.path, label: menu.label }))}
          onClick={({ key }) => navigate(key)}
        />
      </Sider>
      <Layout>
        <Header className="app-header">
          <span className="app-header__title">默认 React 项目模板</span>
          <span className="app-header__meta">React 18 · Ant Design · Tailwind · TypeScript</span>
        </Header>
        <Content className="app-content">
          <Outlet />
        </Content>
      </Layout>
    </Layout>
  );
}
